name: '1K/1K Sweep'

on:
  workflow_dispatch:

jobs:
  get-1k1k-configs:
    runs-on: ubuntu-latest
    outputs:
        search-space-config: ${{ steps.get-1k1k-configs.outputs.search-space-config }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - id: get-1k1k-configs
        run: |
          CONFIG_JSON=$(python3 ${GITHUB_WORKSPACE}/utils/print_configs_json.py ${GITHUB_WORKSPACE}/.github/configs/master.json 1k1k)
          echo "search-space-config=$CONFIG_JSON" >> $GITHUB_OUTPUT
    
  benchmark:
    needs: get-1k1k-configs
    uses: ./.github/workflows/benchmark-tmpl.yml
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.get-1k1k-configs.outputs.search-space-config) }}
    secrets: inherit
    with:
      isl: 1024
      osl: 1024
      runner: ${{ matrix.config.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      tp: ${{ matrix.config.tp }}
      conc: ${{ matrix.config.conc }}

#   collect-results:
#     needs: benchmark
#     steps: