name: Benchmark Template
on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string
      runner:
        required: true
        type: string
      image:
        required: true
        type: string
      model:
        required: true
        type: string
      tp-list:
        required: true
        type: string
      timeout:
        required: true
        type: number

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'
  EXP_NAME: ${{ inputs.exp-name }}
  MODEL: ${{ inputs.model }}
  ISL: ${{ inputs.isl }}
  OSL: ${{ inputs.osl }}
  MAX_MODEL_LEN: ${{ inputs.max-model-len }}
  RANDOM_RANGE_RATIO: ${{ inputs.random-range-ratio }}
  IMAGE: ${{ inputs.image }}
  RUNNER_LABEL: ${{ inputs.runner }}

jobs:
  benchmark:
    runs-on: ${{ inputs.runner }}

    timeout-minutes: ${{ inputs.timeout }}
    strategy:
      fail-fast: false
      matrix:
        tp: ${{ fromJson(inputs.tp-list) }}
        conc: [4, 8, 16, 32, 64]
    name: '${{ inputs.runner }} (tp${{ matrix.tp }} , conc${{ matrix.conc }})'

    env:
      TP: ${{ matrix.tp }}
      CONC: ${{ matrix.conc }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Set result filename
        run: |
          RESULT_FILENAME=${{ env.EXP_NAME }}_tp${{ env.TP }}_conc${{ env.CONC }}_${{ inputs.runner }}
          echo "RESULT_FILENAME=${RESULT_FILENAME}" >> $GITHUB_ENV

      - name: Launch job script
        run: |
          RUNNER_NAME=${{ runner.name }}
          bash ./runners/launch_${RUNNER_NAME%%_*}.sh ${{ inputs.exp-name }}

      - name: Process result
        run: |
          RESULT_FILENAME=${{ env.EXP_NAME }}_tp${{ env.TP }}_conc${{ env.CONC }}_${{ inputs.runner }}
          # Determine framework based on image
          if [[ "${{ inputs.image }}" == *"tensorrt-llm"* ]]; then
            FRAMEWORK="TRT-LLM"
          elif [[ "${{ inputs.image }}" == *"vllm"* ]]; then
            FRAMEWORK="vLLM"
          elif [[ "${{ inputs.image }}" == *"sglang"* ]]; then
            FRAMEWORK="SGLang"
          else
            FRAMEWORK="${{ inputs.runner }}"
          fi
          python3 utils/process_result.py $FRAMEWORK ${{ env.TP }} $RESULT_FILENAME

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXP_NAME }}_tp${{ env.TP }}_conc${{ env.CONC }}_${{ runner.name }}
          path: agg_${{ env.EXP_NAME }}_tp${{ env.TP }}_conc${{ env.CONC }}_${{ inputs.runner }}.json
