name: Benchmark Template
on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string
      runner:
        required: true
        type: string
      image:
        required: true
        type: string
      model:
        required: true
        type: string
      tp-list:
        required: true
        type: string
      timeout:
        required: true
        type: number

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'
  EXP_NAME: ${{ inputs.exp-name }}
  MODEL: ${{ inputs.model }}
  ISL: ${{ inputs.isl }}
  OSL: ${{ inputs.osl }}
  MAX_MODEL_LEN: ${{ inputs.max-model-len }}
  RANDOM_RANGE_RATIO: ${{ inputs.random-range-ratio }}
  IMAGE: ${{ inputs.image }}

jobs:
  benchmark:
    runs-on: ${{ inputs.runner }}

    timeout-minutes: ${{ inputs.timeout }}
    strategy:
      fail-fast: false
      matrix:
        tp: ${{ fromJson(inputs.tp-list) }}
        conc: [1]
    name: '${{ inputs.runner }} (tp${{ matrix.tp }} , conc${{ matrix.conc }})'

    env:
      TP: ${{ matrix.tp }}
      CONC: ${{ matrix.conc }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Set result filename
        run: |
          RESULT_FILENAME=${{ env.EXP_NAME }}_tp${{ env.TP }}_conc${{ env.CONC }}_${{ runner.name }}
          echo "RESULT_FILENAME=${RESULT_FILENAME}" >> $GITHUB_ENV

      - name: Launch job script
        run: |
          RUNNER_NAME=${{ runner.name }}
          bash ./launch_${EXP_NAME%%_*}_${RUNNER_NAME%%_*}.sh

      - name: Process results
        run: |
          python3 process_results.py ${{ inputs.runner }} ${{ env.TP }} ${{ env.RESULT_FILENAME }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RESULT_FILENAME }}
          path: ${{ env.RESULT_FILENAME }}.json
