name: Template - DeepSeek R1

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 180

jobs:
  bmk-h200-fp8:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h200
      image: 'lmsysorg/sglang:v0.4.9.post1-cu126'
      model: 'deepseek-ai/DeepSeek-R1-0528'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'sglang'
      precision: 'fp8'

  bmk-b200-fp8:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: b200
      image: 'lmsysorg/sglang:v0.5.0rc1-cu128-b200'
      model: 'deepseek-ai/DeepSeek-R1-0528'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'sglang'
      precision: 'fp8'

  bmk-b200-trt-fp4:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: b200-trt
      image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post1'
      model: 'nvidia/DeepSeek-R1-0528-FP4'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'trt'
      precision: fp4

  bmk-mi300x-fp8:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi300x
      image: 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_sgl-dev-v0.5.2rc2-mi30x_rc1'
      model: 'deepseek-ai/DeepSeek-R1-0528'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'sglang'
      precision: 'fp8'

  bmk-mi325x-fp8:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi325x
      image: 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_sgl-dev-v0.5.2rc2-mi30x_rc1'
      model: 'deepseek-ai/DeepSeek-R1-0528'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'sglang'
      precision: 'fp8'

  bmk-mi355x-fp8:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi355x
      image: 'lmsysorg/sglang:v0.5.1.post2-rocm700-mi35x'
      model: 'deepseek-ai/DeepSeek-R1-0528'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'sglang'
      precision: 'fp8'

  bmk-mi355x-fp4:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi355x
      image: 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_sgl-dev-v0.5.2rc2_mi35x_rc1'
      model: 'amd/DeepSeek-R1-0528-MXFP4-Preview'
      tp-list: '[8]'
      timeout: ${{ inputs.timeout }}
      framework: 'sglang'
      precision: 'fp4'
