name: Full Sweep Scheduler

concurrency:
  group: benchmark-lock
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  mega-run:
    uses: ./.github/workflows/full-sweep-tmpl.yml
    secrets: inherit
    with:
      run_1k1k: true
      run_8k1k: true
      run_1k8k: true
      use_h100: true
      use_h200: true
      use_b200: true
      use_mi300x: true
      use_mi325x: true
      use_mi355x: false
