name: Template - gpt-oss

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 180

jobs:
  bmk-mi300x:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi300x
      image: 'rocm/vllm-dev:open-mi300-08052025'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  bmk-mi325x:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi325x
      image: 'rocm/vllm-dev:open-mi300-08052025'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  # bmk-mi355x:
  #   uses: ./.github/workflows/benchmark-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: ${{ inputs.exp-name }}
  #     isl: ${{ inputs.isl }}
  #     osl: ${{ inputs.osl }}
  #     max-model-len: ${{ inputs.max-model-len }}
  #     random-range-ratio: ${{ inputs.random-range-ratio }}
  #     runner: mi355x
  #     image: 'rocm/vllm-dev:open-mi355-08052025'
  #     model: 'openai/gpt-oss-120b'
  #     tp-list: '[1, 2]'
  #     timeout: ${{ inputs.timeout }}
  #     framework: 'vllm'
  #     precision: 'fp4'
