name: 'Test - Runner Model Sweep'
run-name: '${{ github.event.inputs.runner }} Sweep'
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner Type'
        required: true
        type: choice
        options:
          - 'h100'
          - 'h200'
          - 'b200'
          - 'h200-trt'
          - 'b200-trt'
          - 'mi300x'
          - 'mi325x'
          - 'mi355x'
          - 'gb200'

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'

jobs:
  bmk-h100:
    if: ${{ inputs.runner == 'h100' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h100-cr_0'
          - 'h100-cr_1'
          - 'h100-cw_0'
          - 'h100-cw_1'
        config:
          - { image: 'vllm/vllm-openai:v0.10.2', model: 'nvidia/Llama-3.3-70B-Instruct-FP8', framework: 'vllm', precision: 'fp8', exp-name: '70b-test' }
          - { image: 'vllm/vllm-openai:v0.10.2', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss-test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'
