name: 'Test - Runner Sweep'
run-name: '${{ github.event.inputs.runner }} Sweep - ${{ github.event.inputs.model }}'
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner Type'
        required: true
        type: choice
        options:
          - 'h100'
          - 'h200'
          - 'b200'
          - 'h200-trt'
          - 'b200-trt'
          - 'mi300x'
          - 'mi325x'
          - 'mi355x'

      image:
        description: 'Docker Image'
        required: true
        type: choice
        options:
          - 'kedarpotdar147/vllm0.1:latest'
          - 'kedarpotdar147/vllm:05'
          - 'vllm/vllm-openai:v0.10.2'
          - 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_vllm_0.10.1_instinct_rc1'
          - 'rocm/vllm-dev:open-mi300-08052025'
          - 'rocm/vllm-dev:open-mi355-08052025'
          - 'lmsysorg/sglang:v0.4.9.post1-cu126'
          - 'lmsysorg/sglang:v0.5.0rc1-cu128-b200'
          - 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_sgl-dev-v0.5.2rc2-mi30x_rc1'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post1'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2'

      model:
        description: 'Model'
        required: true
        type: choice
        options:
          - 'nvidia/Llama-3.3-70B-Instruct-FP8'
          - 'nvidia/Llama-3.3-70B-Instruct-FP4'
          - 'amd/Llama-3.3-70B-Instruct-FP8-KV'
          - 'amd/Llama-3.3-70B-Instruct-MXFP4-Preview'
          - 'deepseek-ai/DeepSeek-R1-0528'
          - 'nvidia/DeepSeek-R1-0528-FP4'
          - 'amd/DeepSeek-R1-0528-MXFP4-Preview'
          - 'openai/gpt-oss-120b'

      framework:
        description: 'Framework'
        required: true
        type: choice
        options:
          - 'vllm'
          - 'sglang'
          - 'trt'

      precision:
        description: 'Precision'
        required: true
        type: choice
        options:
          - 'fp8'
          - 'fp4'

      exp-name:
        description: 'Experiment Name'
        required: true
        type: choice
        options:
          - '70b_test'
          - 'dsr1_test'
          - 'gptoss_test'


env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'

jobs:
  bmk_h100:
    if: ${{ inputs.runner == 'h100' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h100-cr_0'
          - 'h100-cr_1'
          - 'h100-cw_0'
          - 'h100-cw_1'
    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_h200:
    if: ${{ inputs.runner == 'h200' || inputs.runner == 'h200-trt' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h200-cw_0'
          - 'h200-cw_1'
          - 'h200-nb_0'
          - 'h200-nb_1'
          - 'h200-nb_2'
          - 'h200-nb_3'
          - 'h200-nv_0'
          - 'h200-nv_1'
          - 'h200-nv_2'
          - 'h200-nv_3'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_b200:
    if: ${{ inputs.runner == 'b200' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'b200-nv_0'
          - 'b200-nv_1'
          - 'b200-tg_0'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_b200-trt:
    if: ${{ inputs.runner == 'b200-trt' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'b200-nv_0'
          - 'b200-nv_1'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_mi300x:
    if: ${{ inputs.runner == 'mi300x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi300x-amd_0'
          - 'mi300x-amd_1'
          - 'mi300x-amd_2'
          - 'mi300x-amd_3'
          - 'mi300x-amd_4'
          - 'mi300x-cr_0'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_mi325x:
    if: ${{ inputs.runner == 'mi325x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi325x-amd_0'
          - 'mi325x-tw_0'
          - 'mi325x-tw_1'
          - 'mi325x-tw_2'
          - 'mi325x-tw_3'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_mi355x:
    if: ${{ inputs.runner == 'mi355x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi355x-amd_0'
          - 'mi355x-amd_1'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'
