name: Runner Smoke Test

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner'
        required: true
        type: choice
        options:
          - 'h100-cw_0'
          - 'h200-cw_0'
          - 'h200-nb_0'
          - 'h200-nv_0'
          - 'b200-nv_0'
          - 'mi325x-tw_0'
          - 'mi355x-amd_0'
          - 'mi355x-amd_1'
          - 'h100-cr_0'
          - 'h100-cr_1'
          - 'b200-tg_0'
          - 'mi300x-cr_0'
          - 'mi300x-amd_0'
          - 'mi300x-amd_1'
          - 'mi300x-amd_2'
          - 'mi300x-amd_3'
          - 'mi300x-amd_4'
          - 'mi325x-amd_0'

      model:
        description: 'Model Type'
        required: true
        type: choice
        options:
          - 'nvidia/Llama-3.3-70B-Instruct-FP8'
          - 'amd/Llama-3.3-70B-Instruct-FP8-KV'
          - 'deepseek-ai/DeepSeek-R1-0528'

      image:
        description: 'Docker Image'
        required: true
        type: choice
        options:
          - 'kedarpotdar147/vllm0.1:latest'
          - 'kedarpotdar147/vllm:05'
          - 'rocm/vllm-dev:nightly_official_0729_rc1_20250718'
          - 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_vllm_0.9.1_mi35x_alpha'
          - 'lmsysorg/sglang:v0.4.9.post1-cu126'
          - 'lmsysorg/sglang:v0.5.0rc1-cu128-b200'
          - 'lmsysorg/sglang:v0.4.9.post2-rocm630-mi30x'
          - 'lmsysorg/sglang:v0.5.1.post2-rocm700-mi35x'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2'

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'
  EXP_NAME: 'bmk-smoke-test'
  MODEL: ${{ inputs.model }}
  IMAGE: ${{ inputs.image }}
  ISL: 1024
  OSL: 1024
  MAX_MODEL_LEN: 2048
  RANDOM_RANGE_RATIO: 0.8
  TP: 8
  CONC: 4
  RESULT_FILENAME: 'bmk-smoke-test'

jobs:
  bmk-smoke-test:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Launch job script
        run: |
          RUNNER_NAME=${{ inputs.runner }}
          MODEL_HANDLE=$([[ ${{ env.MODEL }} == *70B* ]] && printf '70b' || printf 'dsr1')
          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $MODEL_HANDLE
