name: Workflow Scheduler

concurrency:
  group: benchmark-lock
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      run_70b:
        description: 'Run Model 70B'
        required: false
        type: boolean
        default: true

      run_dsr1:
        description: 'Run Model DSR1'
        required: false
        type: boolean
        default: true

      run_gptoss:
        description: 'Run Model gpt-oss'
        required: false
        type: boolean
        default: true

      run_1k1k:
        description: 'Run 1K/1K'
        required: false
        type: boolean
        default: true

      run_8k1k:
        description: 'Run 8K/1K'
        required: false
        type: boolean
        default: true

      run_1k8k:
        description: 'Run 1K/8K'
        required: false
        type: boolean
        default: true

  schedule:
    - cron: '0 5 * * *'

jobs:
  _70b-1k1k:
    if: ${{ inputs.run_70b }} && ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8

  dsr1-1k1k:
    if: ${{ inputs.run_dsr1 }} && ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8

  gptoss-1k1k:
    if: ${{ inputs.run_gptoss }} && ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8

  _70b-8k1k:
    if: ${{ inputs.run_70b }} && ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
  
  dsr1-8k1k:
    if: ${{ inputs.run_dsr1 }} && ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8

  _70b-1k8k:
    if: ${{ inputs.run_70b }} && ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      timeout: 240

  dsr1-1k8k:
    if: ${{ inputs.run_dsr1 }} && ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
