name: Workflow Scheduler

# concurrency:
#   group: benchmark-lock
#   cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

vars:
  USE_H100: true
  USE_H200: true
  USE_B200: true
  USE_MI300X: true
  USE_MI325X: true
  USE_MI355X: false

jobs:
  _70b-1k1k:
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h100: ${{ vars.USE_H100 }}
      use_h200: ${{ vars.USE_H200 }}
      use_b200: ${{ vars.USE_B200 }}
      use_mi300x: ${{ vars.USE_MI300X }}
      use_mi325x: ${{ vars.USE_MI325X }}
      use_mi355x: ${{ vars.USE_MI355X }}

  collect-70b-1k1k-results:
    needs: _70b-1k1k
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: '70b_1k1k'

  # dsr1-1k1k:
  #   uses: ./.github/workflows/dsr1-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'dsr1_1k1k'
  #     isl: 1024
  #     osl: 1024
  #     max-model-len: 2048
  #     random-range-ratio: 0.8

  # collect-dsr1-1k1k-results:
  #   needs: dsr1-1k1k
  #   if: ${{ always() && !cancelled() }}
  #   uses: ./.github/workflows/collect-results.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'dsr1_1k1k'

  # gptoss-1k1k:
  #   uses: ./.github/workflows/gptoss-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'gptoss_1k1k'
  #     isl: 1024
  #     osl: 1024
  #     max-model-len: 2048
  #     random-range-ratio: 0.8

  # collect-gptoss-1k1k-results:
  #   needs: gptoss-1k1k
  #   if: ${{ always() && !cancelled() }}
  #   uses: ./.github/workflows/collect-results.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'gptoss_1k1k'

  # _70b-8k1k:
  #   uses: ./.github/workflows/70b-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: '70b_8k1k'
  #     isl: 8192
  #     osl: 1024
  #     max-model-len: 9216
  #     random-range-ratio: 0.8
  # 
  # dsr1-8k1k:
  #   uses: ./.github/workflows/dsr1-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'dsr1_8k1k'
  #     isl: 8192
  #     osl: 1024
  #     max-model-len: 9216
  #     random-range-ratio: 0.8

  # _70b-1k8k:
  #   uses: ./.github/workflows/70b-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: '70b_1k8k'
  #     isl: 1024
  #     osl: 8192
  #     max-model-len: 9216
  #     random-range-ratio: 0.8
  #     timeout: 240

  # dsr1-1k8k:
  #   uses: ./.github/workflows/dsr1-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'dsr1_1k8k'
  #     isl: 1024
  #     osl: 8192
  #     max-model-len: 9216
  #     random-range-ratio: 0.8

  # gptoss-1k8k:
  #   uses: ./.github/workflows/gptoss-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'gptoss_1k8k'
  #     isl: 1024
  #     osl: 8192
  #     max-model-len: 9216
  #     random-range-ratio: 0.8
