name: Workflow Scheduler

concurrency:
  group: benchmark-lock
  cancel-in-progress: false

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 1 * * *'

jobs:
  cleanup:
    uses: ./.github/workflows/cluster-cleanup.yml

  # _70b-1k1k:
  #   needs: cleanup
  #   uses: ./.github/workflows/70b-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: '70b_1k1k'
  #     isl: 1024
  #     osl: 1024
  #     max-model-len: 2048
  #     random-range-ratio: 0.8
    
  # dsv3-1k1k:
  #   needs: cleanup
  #   uses: ./.github/workflows/dsv3-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'dsv3_1k1k'
  #     isl: 1024
  #     osl: 1024
  #     max-model-len: 2048
  #     random-range-ratio: 0.8

  _70b-8k1k:
    needs: cleanup
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8

  dsv3-8k1k:
    needs: cleanup
    uses: ./.github/workflows/dsv3-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsv3_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8

  # _70b-1k8k:
  #   needs: cleanup
  #   uses: ./.github/workflows/70b-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: '70b_1k8k'
  #     isl: 1024
  #     osl: 8192
  #     max-model-len: 9216
  #     random-range-ratio: 0.8
  #     timeout: 240

  # dsv3-1k8k:
  #   needs: cleanup
  #   uses: ./.github/workflows/dsv3-tmpl.yml
  #   secrets: inherit
  #   with:
  #     exp-name: 'dsv3_1k8k'
  #     isl: 1024
  #     osl: 8192
  #     max-model-len: 9216
  #     random-range-ratio: 0.8
